title: "Chrom-Pain"
lang: fr
author:
  - name: "Dr Philippe MICHEL"
    affiliations:
      name: "Hôpital \\textsc{novo}"
      department: "Unité de Soutien à la Recherche Clinique"
format:
 titlepage-pdf:
  titlepage: bg-image
  titlepage-bg-image: "novo_usrc.png"
  logo-space-after: "0\\baselineskip"
  documentclass: scrreprt
  number-sections: true
  titlepage-footer: "D\\up{r} Suzanne \\textsc{Borrhomée}\\newline \\newline Service de réanimation et médecine néo-natale - Hôpital \\textsc{novo} (Site Pontoise)\\newline \\newline Chef de projet : M\\up{me} Mathilde WLODARCZYK\\newline \\newline Évaluation de la douleur chez les nouveaux nés hospitalisés pour une anomalie
chromosomique sévère - RNIPH\\newline \\today"
titlepage-theme:
  title-fontstyle: ["Huge", "bfseries"]
  title-color: novo
  subtitle-color: novo
  subtitle-fontstyle: ["huge"]
  logo-size: "0.2\\textheight"
  vrule-width: "0.1cm"
  vrule-color: novo
include-in-header:
   text: |
    \definecolor{novo}{HTML}{27484b}
    \usepackage{siunitx}
    \AddToHook{env/tabular/before}{\addfontfeatures{Numbers=Monospaced}}
    \AddToHook{env/longtable/before}{\addfontfeatures{Numbers=Monospaced}}
    \usepackage{alphabeta}
df-print : kable
jss-pdf:
  keep-tex: true
pdf-engine: lualatex
keep-tex: true
number-sections: true
toc: true
lof: false
lot: false
mainfont: Fira-sans
mainfontoptions:
  - Ligatures=TeX
monofont: Fira Mono
sansfontoptions:
  - Ligatures=TeX
fig-cap-location: bottom
tbl-cap-location: top
classoption: [french, fontsize=10pt]
papersize: a4
editor: source
bibliography: stat.bib
cite-method: biblatex
#csl: jama.csl
#reference-location: margin
#citation-location: margin
license: "MIT"
echo: false
warning: false
message: false
cache: false
